CREATE TABLE user_info (
    NUMBER INT UNSIGNED NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(100) NOT NULL,
    USER_PW VARCHAR(100) NOT NULL,
    PRIMARY KEY(NUMBER)
);

CREATE TABLE user_check (
    WEEK VARCHAR(20) NOT NULL
    USER_ID VARCHAR(100) NOT NULL,
    DATE_CHECK DATE NOT NULL,
    CHECK_CHECK VARCHAR(20) NOT NULL
);